#include <map>
#include <string>
#include <vector>
#include <array>

extern std::array<std::vector<bool>, 5> lower_a;
extern std::array<std::vector<bool>, 5> lower_b;
extern std::array<std::vector<bool>, 5> lower_c;
extern std::array<std::vector<bool>, 5> lower_d;
extern std::array<std::vector<bool>, 5> lower_e;
extern std::array<std::vector<bool>, 5> lower_f;
extern std::array<std::vector<bool>, 5> lower_g;
extern std::array<std::vector<bool>, 5> lower_h;
extern std::array<std::vector<bool>, 5> lower_i;
extern std::array<std::vector<bool>, 5> lower_j;
extern std::array<std::vector<bool>, 5> lower_k;
extern std::array<std::vector<bool>, 5> lower_l;
extern std::array<std::vector<bool>, 5> lower_m;
extern std::array<std::vector<bool>, 5> lower_n;
extern std::array<std::vector<bool>, 5> lower_o;
extern std::array<std::vector<bool>, 5> lower_p;
extern std::array<std::vector<bool>, 5> lower_q;
extern std::array<std::vector<bool>, 5> lower_r;
extern std::array<std::vector<bool>, 5> lower_s;
extern std::array<std::vector<bool>, 5> lower_t;
extern std::array<std::vector<bool>, 5> lower_u;
extern std::array<std::vector<bool>, 5> lower_v;
extern std::array<std::vector<bool>, 5> lower_w;
extern std::array<std::vector<bool>, 5> lower_x;
extern std::array<std::vector<bool>, 5> lower_y;
extern std::array<std::vector<bool>, 5> lower_z;

extern std::array<std::vector<bool>, 5> upper_a;
extern std::array<std::vector<bool>, 5> upper_b;
extern std::array<std::vector<bool>, 5> upper_c;
extern std::array<std::vector<bool>, 5> upper_d;
extern std::array<std::vector<bool>, 5> upper_e;
extern std::array<std::vector<bool>, 5> upper_f;
extern std::array<std::vector<bool>, 5> upper_g;
extern std::array<std::vector<bool>, 5> upper_h;
extern std::array<std::vector<bool>, 5> upper_i;
extern std::array<std::vector<bool>, 5> upper_j;
extern std::array<std::vector<bool>, 5> upper_k;
extern std::array<std::vector<bool>, 5> upper_l;
extern std::array<std::vector<bool>, 5> upper_m;
extern std::array<std::vector<bool>, 5> upper_n;
extern std::array<std::vector<bool>, 5> upper_o;
extern std::array<std::vector<bool>, 5> upper_p;
extern std::array<std::vector<bool>, 5> upper_q;
extern std::array<std::vector<bool>, 5> upper_r;
extern std::array<std::vector<bool>, 5> upper_s;
extern std::array<std::vector<bool>, 5> upper_t;
extern std::array<std::vector<bool>, 5> upper_u;
extern std::array<std::vector<bool>, 5> upper_v;
extern std::array<std::vector<bool>, 5> upper_w;
extern std::array<std::vector<bool>, 5> upper_x;
extern std::array<std::vector<bool>, 5> upper_y;
extern std::array<std::vector<bool>, 5> upper_z;

extern std::array<std::vector<bool>, 5> zero;
extern std::array<std::vector<bool>, 5> one;
extern std::array<std::vector<bool>, 5> two;
extern std::array<std::vector<bool>, 5> three;
extern std::array<std::vector<bool>, 5> four;
extern std::array<std::vector<bool>, 5> five;
extern std::array<std::vector<bool>, 5> six;
extern std::array<std::vector<bool>, 5> seven;
extern std::array<std::vector<bool>, 5> eight;
extern std::array<std::vector<bool>, 5> nine;

extern std::array<std::vector<bool>, 5> exclamation;
extern std::array<std::vector<bool>, 5> question;
extern std::array<std::vector<bool>, 5> comma;
extern std::array<std::vector<bool>, 5> forward_slash;
extern std::array<std::vector<bool>, 5> backward_slash;
extern std::array<std::vector<bool>, 5> equals;
extern std::array<std::vector<bool>, 5> asterisk;
extern std::array<std::vector<bool>, 5> plus_symbol;
extern std::array<std::vector<bool>, 5> minus_symbol;
extern std::array<std::vector<bool>, 5> double_quotation;
extern std::array<std::vector<bool>, 5> hashtag;
extern std::array<std::vector<bool>, 5> dollar;
extern std::array<std::vector<bool>, 5> percentage;
extern std::array<std::vector<bool>, 5> apostrophe;
extern std::array<std::vector<bool>, 5> open_bracket;
extern std::array<std::vector<bool>, 5> closed_bracket;
extern std::array<std::vector<bool>, 5> open_squared_bracket;
extern std::array<std::vector<bool>, 5> closed_squared_bracket;
extern std::array<std::vector<bool>, 5> open_curly_bracket;
extern std::array<std::vector<bool>, 5> closed_curly_bracket;
extern std::array<std::vector<bool>, 5> colon;
extern std::array<std::vector<bool>, 5> semi_colon;
extern std::array<std::vector<bool>, 5> period;
extern std::array<std::vector<bool>, 5> less_than;
extern std::array<std::vector<bool>, 5> greater_than;
extern std::array<std::vector<bool>, 5> up_arrow;
extern std::array<std::vector<bool>, 5> underscore;
extern std::array<std::vector<bool>, 5> tilde;
extern std::array<std::vector<bool>, 5> unknown;
extern std::array<std::vector<bool>, 5> space;

extern std::map<char, std::array<std::vector<bool>, 5>> character_mapping;