#include <map>
#include <string>
#include <array>
using namespace std;

extern array<array<bool, 3>, 5> lower_a;
extern array<array<bool, 3>, 5> lower_b;
extern array<array<bool, 3>, 5> lower_c;
extern array<array<bool, 3>, 5> lower_d;
extern array<array<bool, 3>, 5> lower_e;
extern array<array<bool, 3>, 5> lower_f;
extern array<array<bool, 3>, 5> lower_g;
extern array<array<bool, 3>, 5> lower_h;
extern array<array<bool, 3>, 5> lower_i;
extern array<array<bool, 3>, 5> lower_j;
extern array<array<bool, 3>, 5> lower_k;
extern array<array<bool, 3>, 5> lower_l;
extern array<array<bool, 3>, 5> lower_m;
extern array<array<bool, 3>, 5> lower_n;
extern array<array<bool, 3>, 5> lower_o;
extern array<array<bool, 3>, 5> lower_p;
extern array<array<bool, 3>, 5> lower_q;
extern array<array<bool, 3>, 5> lower_r;
extern array<array<bool, 3>, 5> lower_s;
extern array<array<bool, 3>, 5> lower_t;
extern array<array<bool, 3>, 5> lower_u;
extern array<array<bool, 3>, 5> lower_v;
extern array<array<bool, 3>, 5> lower_w;
extern array<array<bool, 3>, 5> lower_x;
extern array<array<bool, 3>, 5> lower_y;
extern array<array<bool, 3>, 5> lower_z;

extern array<array<bool, 3>, 5> upper_a;
extern array<array<bool, 3>, 5> upper_b;
extern array<array<bool, 3>, 5> upper_c;
extern array<array<bool, 3>, 5> upper_d;
extern array<array<bool, 3>, 5> upper_e;
extern array<array<bool, 3>, 5> upper_f;
extern array<array<bool, 3>, 5> upper_g;
extern array<array<bool, 3>, 5> upper_h;
extern array<array<bool, 3>, 5> upper_i;
extern array<array<bool, 3>, 5> upper_j;
extern array<array<bool, 3>, 5> upper_k;
extern array<array<bool, 3>, 5> upper_l;
extern array<array<bool, 3>, 5> upper_m;
extern array<array<bool, 3>, 5> upper_n;
extern array<array<bool, 3>, 5> upper_o;
extern array<array<bool, 3>, 5> upper_p;
extern array<array<bool, 3>, 5> upper_q;
extern array<array<bool, 3>, 5> upper_r;
extern array<array<bool, 3>, 5> upper_s;
extern array<array<bool, 3>, 5> upper_t;
extern array<array<bool, 3>, 5> upper_u;
extern array<array<bool, 3>, 5> upper_v;
extern array<array<bool, 3>, 5> upper_w;
extern array<array<bool, 3>, 5> upper_x;
extern array<array<bool, 3>, 5> upper_y;
extern array<array<bool, 3>, 5> upper_z;

extern array<array<bool, 3>, 5> zero;
extern array<array<bool, 3>, 5> one;
extern array<array<bool, 3>, 5> two;
extern array<array<bool, 3>, 5> three;
extern array<array<bool, 3>, 5> four;
extern array<array<bool, 3>, 5> five;
extern array<array<bool, 3>, 5> six;
extern array<array<bool, 3>, 5> seven;
extern array<array<bool, 3>, 5> eight;
extern array<array<bool, 3>, 5> nine;

extern array<array<bool, 3>, 5> exclamation;
extern array<array<bool, 3>, 5> question;
extern array<array<bool, 3>, 5> comma;
extern array<array<bool, 3>, 5> forward_slash;
extern array<array<bool, 3>, 5> backward_slash;
extern array<array<bool, 3>, 5> equals;
extern array<array<bool, 3>, 5> asterisk;
extern array<array<bool, 3>, 5> plus_symbol;
extern array<array<bool, 3>, 5> minus_symbol;
extern array<array<bool, 3>, 5> double_quotation;
extern array<array<bool, 3>, 5> hashtag;
extern array<array<bool, 3>, 5> dollar;
extern array<array<bool, 3>, 5> percentage;
extern array<array<bool, 3>, 5> apostrophe;
extern array<array<bool, 3>, 5> open_bracket;
extern array<array<bool, 3>, 5> closed_bracket;
extern array<array<bool, 3>, 5> open_squared_bracket;
extern array<array<bool, 3>, 5> closed_squared_bracket;
extern array<array<bool, 3>, 5> open_curly_bracket;
extern array<array<bool, 3>, 5> closed_curly_bracket;
extern array<array<bool, 3>, 5> colon;
extern array<array<bool, 3>, 5> semi_colon;
extern array<array<bool, 3>, 5> less_than;
extern array<array<bool, 3>, 5> greater_than;
extern array<array<bool, 3>, 5> up_arrow;
extern array<array<bool, 3>, 5> underscore;
extern array<array<bool, 3>, 5> unknown;

extern map<char, array<array<bool, 3>, 5>> character_mapping;